// frontend/src/app/dashboard/page.tsx
import PassesList from "@/components/events/PassesList";
import Card from "@/components/ui/card";

export default function DashboardPage() {
  return (
    <div className="mx-auto max-w-6xl space-y-6 p-6">
      <h1 className="text-2xl font-semibold">Dashboard</h1>

      <p className="text-sm text-muted-foreground">
        Your personalized dashboard — upcoming passes and recent sightings will appear here.
      </p>

      <section className="space-y-4">
        <Card>
          <h2 className="font-semibold text-lg">Next ISS Passes</h2>
          <p className="text-sm text-muted-foreground">Predictions are generated by the astro service (mocked locally).</p>
        </Card>

        <div>
          <PassesList />
        </div>
      </section>
    </div>
  );
}
